# Generated by Django 5.2.16 on 2026-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_reminder_enabled_trip_reminder_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='priority',
            field=models.CharField(default='Bắt buộc', max_length=50),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(default='Phượt', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.CharField(default='Xe máy', max_length=100),
        ),
    ]
